#
# docker-compose.yml
#
services:
  #
  # peer server
  #
  peer-server:
    build:
      context: ./peer-server
      dockerfile: Dockerfile
    ports:
      - "9500:9500"

  # #
  # # TURN server
  # #
  # # docker run -d -p 3478:3478 -p 3478:3478/udp -p 5349:5349 -p 5349:5349/udp -p 49152-65535:49152-65535/udp coturn/coturn
  # coturn:
  #   image: coturn/coturn
  #   ports:
  #     - 3478:3478
  #     - 3478:3478/udp
  #     - 5349:5349
  #     - 5349:5349/udp
  #     - 49152-65535:49152-65535/udp

  #
  # peer client
  #
  client:
    image: nginx
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NGINX_HOST: client
      NGINX_PORT: 8000
    volumes:
      - ./client/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/dist:/usr/share/nginx/html

  # reverse-proxy:
  #   image: 

  # #
  # # https portal
  # #
  # https-portal:
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - client
  #   restart: always
  #   environment:
  #     DOMAINS: 'espresso.local -> http://client:8000'
  #     STAGE: 'local'
  #     # STAGE: 'production' # Don't use production until staging works
  #     # FORCE_RENEW: 'true'
  #     WEBSOCKET: true
  #   volumes:
  #     - https-portal-data:/var/lib/https-portal

  # #
  # # forward proxy
  # #
  # proxy:
  #   image: ubuntu/squid
  #   ports:
  #     - '3128:3128'
  #   environment:
  #     TZ: 'UTC'
  #   volumes:
  #     - squid_data:/var/spool/squid
  #     # - ./squid/squid.conf:/etc/squid/squid.conf

# volumes:
  # https-portal-data: null
  # squid_data: null
  # database_data: null
  # phpmyadmin_data: null
  # mail_data: null
