#
# docker-compose.yml
#
services:
  #
  #
  #
  server:
    image: peerjs/peerjs-server:1.1.0-rc.2
    ports:
      - 9000:9000

  client:
    image: nginx
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    environment:
      NGINX_HOST: www.example.com
      NGINX_PORT: 80
    volumes:
      - ./client/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./client/dist:/usr/share/nginx/html
# networks:
#   backend: {}

# volumes:
#   database_data: null
#   phpmyadmin_data: null
#   mail_data: null
